### ISSUE TITLE
"Dependency Combobulator" Link is broken in README.md file

### ISSUE THREAD

**Issue by KumarRupace** [sottlmarek/DevSecOps#25]
Under "OSS and Dependency management" section.
_"Dependency Combobulator"_ Link is  **broken in README.md** file. There is a missing `"/"` in actual link.

At line no 111.
![image](https://user-images.githubusercontent.com/29791721/156494867-3614779e-ecf3-47fa-98f7-7de3b5f10f88.png)

**Comment by sottlmarek** [comment]
Thanks for contribution!
