### ISSUE TITLE
Error while opening file "DevSecOps/.github/ISSUE_TEMPLATE/devsecops-issue-tamplate.md"

### ISSUE THREAD

**Issue by kumarrupace** [sottlmarek/DevSecOps#27]
Looks like there is some error as per (PIC 1)

It may be due to two files having quite similar name but one to them having typo (PIC 2)

### PIC 1

![image](https://user-images.githubusercontent.com/29791721/156868922-73912b42-ec47-49a1-88ca-6f1c30ab9cd7.png)

### PIC 2
![image](https://user-images.githubusercontent.com/29791721/156868979-efdda09a-9da8-49c2-abd8-0b41aecf5a5f.png)

**Comment by sottlmarek** [comment]
Thank you for reporting this, I will take a look on that.
